const express = require('express');
const db = require('../../../db');
const { organisationValue } = require('../../utils/organisationScope');
require('../../services/business/cybersecurity-governance-transaction.service');

const router = express.Router();
const org = (req) => organisationValue(req.organisationId || req.user?.organisation_id);
const actor = (req) => req.user?.id || req.user?.userId || null;
const key = (req) => req.get('Idempotency-Key') || req.body?.idempotencyKey;
const handle = (res, next, fn, status = 200) => Promise.resolve(fn()).then((data) => res.status(status).json(data)).catch(next);

router.get('/assets', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM cybersecurity_assets WHERE organisation_id=$1 ORDER BY created_at DESC',[org(req)])).rows));
router.post('/assets', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO cybersecurity_assets (organisation_id,asset_number,name,asset_type,owner_user_id,confidentiality,integrity_requirement,availability_requirement,criticality,next_review_at,evidence,idempotency_key,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[org(req),req.body.assetNumber,req.body.name,req.body.assetType,req.body.ownerUserId,req.body.confidentiality||'internal',req.body.integrityRequirement||'medium',req.body.availabilityRequirement||'medium',req.body.criticality||'medium',req.body.nextReviewAt,req.body.evidence||[],key(req),actor(req)])).rows[0],201));

router.get('/controls', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM cybersecurity_controls WHERE organisation_id=$1 ORDER BY created_at DESC',[org(req)])).rows));
router.post('/controls', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO cybersecurity_controls (organisation_id,asset_id,control_number,control_family,title,description,owner_user_id,verification_frequency,next_verification_at,evidence,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[org(req),req.body.assetId||null,req.body.controlNumber,req.body.controlFamily,req.body.title,req.body.description,req.body.ownerUserId,req.body.verificationFrequency||null,req.body.nextVerificationAt||null,req.body.evidence||[],key(req)])).rows[0],201));
router.post('/controls/:id/verify', (req,res,next) => handle(res,next,async () => (await db.pool.query(`UPDATE cybersecurity_controls SET implementation_status='verified',last_verified_at=NOW(),next_verification_at=$1,evidence=$2,result=$3,updated_at=NOW() WHERE id=$4 AND organisation_id=$5 RETURNING *`,[req.body.nextVerificationAt,req.body.evidence||[],req.body.result,req.params.id,org(req)])).rows[0]));

router.get('/vulnerabilities', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM cybersecurity_vulnerabilities WHERE organisation_id=$1 ORDER BY detected_at DESC',[org(req)])).rows));
router.post('/vulnerabilities', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO cybersecurity_vulnerabilities (organisation_id,asset_id,vulnerability_number,title,description,severity,source,due_at,owner_user_id,remediation_plan,evidence,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[org(req),req.body.assetId||null,req.body.vulnerabilityNumber,req.body.title,req.body.description,req.body.severity,req.body.source,req.body.dueAt||null,req.body.ownerUserId,req.body.remediationPlan||null,req.body.evidence||[],key(req)])).rows[0],201));

router.get('/incidents', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM cybersecurity_incidents WHERE organisation_id=$1 ORDER BY occurred_at DESC',[org(req)])).rows));
router.post('/incidents', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO cybersecurity_incidents (organisation_id,incident_number,title,description,severity,occurred_at,owner_user_id,affected_assets,decision_log,containment_actions,evidence,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[org(req),req.body.incidentNumber,req.body.title,req.body.description,req.body.severity,req.body.occurredAt,req.body.ownerUserId,req.body.affectedAssets||[],req.body.decisionLog||[],req.body.containmentActions||[],req.body.evidence||[],key(req)])).rows[0],201));
router.post('/incidents/:id/close', (req,res,next) => handle(res,next,async () => (await db.pool.query(`UPDATE cybersecurity_incidents SET status='closed',root_cause=$1,lessons_learned=$2,evidence=$3,updated_at=NOW() WHERE id=$4 AND organisation_id=$5 RETURNING *`,[req.body.rootCause,req.body.lessonsLearned,req.body.evidence||[],req.params.id,org(req)])).rows[0]));

router.get('/access-reviews', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM cybersecurity_access_reviews WHERE organisation_id=$1 ORDER BY reviewed_at DESC',[org(req)])).rows));
router.post('/access-reviews', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO cybersecurity_access_reviews (organisation_id,review_number,scope,reviewer_user_id,conclusion,exceptions,remediation_actions,evidence,next_review_at,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[org(req),req.body.reviewNumber,req.body.scope,req.body.reviewerUserId||actor(req),req.body.conclusion,req.body.exceptions||[],req.body.remediationActions||[],req.body.evidence||[],req.body.nextReviewAt,key(req)])).rows[0],201));

router.get('/exercises', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM cybersecurity_exercises WHERE organisation_id=$1 ORDER BY performed_at DESC',[org(req)])).rows));
router.post('/exercises', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO cybersecurity_exercises (organisation_id,exercise_number,exercise_type,scenario,owner_user_id,result,conclusion,improvement_actions,evidence,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[org(req),req.body.exerciseNumber,req.body.exerciseType,req.body.scenario,req.body.ownerUserId||actor(req),req.body.result,req.body.conclusion,req.body.improvementActions||[],req.body.evidence||[],key(req)])).rows[0],201));

router.get('/alerts', (req,res,next) => handle(res,next,async () => (await db.pool.query(`SELECT 'asset_review' AS alert_type,id,asset_number AS reference,next_review_at AS due_at FROM cybersecurity_assets WHERE organisation_id=$1 AND next_review_at<=NOW() AND status='active' UNION ALL SELECT 'control_verification',id,control_number,next_verification_at FROM cybersecurity_controls WHERE organisation_id=$1 AND next_verification_at IS NOT NULL AND next_verification_at<=NOW() AND implementation_status NOT IN ('retired') UNION ALL SELECT 'vulnerability_due',id,vulnerability_number,due_at FROM cybersecurity_vulnerabilities WHERE organisation_id=$1 AND due_at IS NOT NULL AND due_at<=NOW() AND status NOT IN ('mitigated','accepted','closed') ORDER BY due_at`,[org(req)])).rows));

module.exports = router;
