const express = require('express');
const db = require('../../../db');
const { organisationValue } = require('../../utils/organisationScope');
require('../../services/business/enterprise-business-continuity-transaction.service');

const router = express.Router();
const org = (req) => organisationValue(req.organisationId || req.user?.organisation_id);
const actor = (req) => req.user?.id || req.user?.userId || null;
const key = (req) => req.get('Idempotency-Key') || req.body?.idempotencyKey;
const handle = (res, next, fn, status = 200) => Promise.resolve(fn()).then((data) => res.status(status).json(data)).catch(next);

router.get('/processes', (req, res, next) => handle(res, next, async () => (await db.pool.query('SELECT * FROM enterprise_business_processes WHERE organisation_id=$1 ORDER BY created_at DESC', [org(req)])).rows));
router.post('/processes', (req, res, next) => handle(res, next, async () => (await db.pool.query(`INSERT INTO enterprise_business_processes (organisation_id,process_number,name,description,owner_user_id,criticality,maximum_tolerable_downtime_minutes,recovery_time_objective_minutes,recovery_point_objective_minutes,status,next_review_at,evidence,idempotency_key,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`, [org(req),req.body.processNumber,req.body.name,req.body.description,req.body.ownerUserId,req.body.criticality||'high',req.body.maximumTolerableDowntimeMinutes,req.body.recoveryTimeObjectiveMinutes,req.body.recoveryPointObjectiveMinutes??null,req.body.status||'active',req.body.nextReviewAt,req.body.evidence||[],key(req),actor(req)])).rows[0], 201));

router.get('/dependencies', (req, res, next) => handle(res, next, async () => (await db.pool.query('SELECT * FROM enterprise_process_dependencies WHERE organisation_id=$1 ORDER BY created_at DESC', [org(req)])).rows));
router.post('/dependencies', (req, res, next) => handle(res, next, async () => (await db.pool.query(`INSERT INTO enterprise_process_dependencies (organisation_id,process_id,dependency_type,dependency_reference,description,criticality,fallback_description,owner_user_id,evidence,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`, [org(req),req.body.processId,req.body.dependencyType,req.body.dependencyReference,req.body.description,req.body.criticality||'high',req.body.fallbackDescription||null,req.body.ownerUserId||actor(req),req.body.evidence||[],key(req)])).rows[0], 201));

router.get('/plans', (req, res, next) => handle(res, next, async () => (await db.pool.query('SELECT * FROM enterprise_continuity_plans WHERE organisation_id=$1 ORDER BY created_at DESC', [org(req)])).rows));
router.post('/plans', (req, res, next) => handle(res, next, async () => (await db.pool.query(`INSERT INTO enterprise_continuity_plans (organisation_id,process_id,plan_number,title,scenario,activation_conditions,owner_user_id,procedures,resources,evidence,status,next_review_at,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`, [org(req),req.body.processId,req.body.planNumber,req.body.title,req.body.scenario,req.body.activationConditions,req.body.ownerUserId,req.body.procedures||[],req.body.resources||[],req.body.evidence||[],req.body.status||'draft',req.body.nextReviewAt,key(req)])).rows[0], 201));
router.post('/plans/:id/activate', (req, res, next) => handle(res, next, async () => (await db.pool.query(`UPDATE enterprise_continuity_plans SET status='active', evidence=evidence || $3::jsonb, updated_at=NOW() WHERE id=$1 AND organisation_id=$2 RETURNING *`, [req.params.id,org(req),JSON.stringify(req.body.evidence||[])])).rows[0]));

router.get('/procedures', (req, res, next) => handle(res, next, async () => (await db.pool.query('SELECT * FROM enterprise_recovery_procedures WHERE organisation_id=$1 ORDER BY created_at DESC', [org(req)])).rows));
router.post('/procedures', (req, res, next) => handle(res, next, async () => (await db.pool.query(`INSERT INTO enterprise_recovery_procedures (organisation_id,plan_id,procedure_number,title,steps,responsible_user_id,expected_duration_minutes,evidence,status,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`, [org(req),req.body.planId,req.body.procedureNumber,req.body.title,req.body.steps||[],req.body.responsibleUserId,req.body.expectedDurationMinutes||null,req.body.evidence||[],req.body.status||'draft',key(req)])).rows[0], 201));

router.get('/exercises', (req, res, next) => handle(res, next, async () => (await db.pool.query('SELECT * FROM enterprise_continuity_exercises WHERE organisation_id=$1 ORDER BY executed_at DESC', [org(req)])).rows));
router.post('/exercises', (req, res, next) => handle(res, next, async () => (await db.pool.query(`INSERT INTO enterprise_continuity_exercises (organisation_id,plan_id,exercise_number,scenario,executed_at,result,conclusion,observations,improvements,evidence,executed_by,idempotency_key) VALUES ($1,$2,$3,$4,COALESCE($5,NOW()),$6,$7,$8,$9,$10,$11,$12) RETURNING *`, [org(req),req.body.planId,req.body.exerciseNumber,req.body.scenario,req.body.executedAt||null,req.body.result,req.body.conclusion,req.body.observations||[],req.body.improvements||[],req.body.evidence||[],actor(req),key(req)])).rows[0], 201));

router.get('/events', (req, res, next) => handle(res, next, async () => (await db.pool.query('SELECT * FROM enterprise_major_events WHERE organisation_id=$1 ORDER BY started_at DESC', [org(req)])).rows));
router.post('/events', (req, res, next) => handle(res, next, async () => (await db.pool.query(`INSERT INTO enterprise_major_events (organisation_id,plan_id,event_number,title,description,severity,started_at,status,decision_log,evidence,owner_user_id,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,COALESCE($7,NOW()),$8,$9,$10,$11,$12) RETURNING *`, [org(req),req.body.planId||null,req.body.eventNumber,req.body.title,req.body.description,req.body.severity||'high',req.body.startedAt||null,req.body.status||'active',req.body.decisionLog||[],req.body.evidence||[],req.body.ownerUserId||actor(req),key(req)])).rows[0], 201));
router.post('/events/:id/close', (req, res, next) => handle(res, next, async () => (await db.pool.query(`UPDATE enterprise_major_events SET status='closed', ended_at=COALESCE($3,NOW()), lessons_learned=$4, evidence=evidence || $5::jsonb, updated_at=NOW() WHERE id=$1 AND organisation_id=$2 RETURNING *`, [req.params.id,org(req),req.body.endedAt||null,req.body.lessonsLearned,JSON.stringify(req.body.evidence||[])])).rows[0]));

router.get('/reviews', (req, res, next) => handle(res, next, async () => (await db.pool.query('SELECT * FROM enterprise_continuity_reviews WHERE organisation_id=$1 ORDER BY reviewed_at DESC', [org(req)])).rows));
router.post('/reviews', (req, res, next) => handle(res, next, async () => (await db.pool.query(`INSERT INTO enterprise_continuity_reviews (organisation_id,plan_id,review_number,reviewer_user_id,reviewed_at,conclusion,evidence,next_review_at,idempotency_key) VALUES ($1,$2,$3,$4,COALESCE($5,NOW()),$6,$7,$8,$9) RETURNING *`, [org(req),req.body.planId,req.body.reviewNumber,req.body.reviewerUserId||actor(req),req.body.reviewedAt||null,req.body.conclusion,req.body.evidence||[],req.body.nextReviewAt,key(req)])).rows[0], 201));

router.get('/alerts', (req, res, next) => handle(res, next, async () => (await db.pool.query(`SELECT 'process_review' AS alert_type,id,process_number AS reference,next_review_at AS due_at FROM enterprise_business_processes WHERE organisation_id=$1 AND next_review_at<=NOW() AND status='active' UNION ALL SELECT 'plan_review',id,plan_number,next_review_at FROM enterprise_continuity_plans WHERE organisation_id=$1 AND next_review_at<=NOW() AND status IN ('approved','active') ORDER BY due_at`, [org(req)])).rows));

module.exports = router;
