const express = require('express');
const db = require('../../../db');
const { organisationValue } = require('../../utils/organisationScope');
require('../../services/business/facilities-management-transaction.service');

const router = express.Router();
const org = (req) => organisationValue(req.organisationId || req.user?.organisation_id);
const handle = (res, next, fn, status = 200) => Promise.resolve(fn()).then((data) => res.status(status).json(data)).catch(next);

router.get('/sites', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM facilities_sites WHERE organisation_id=$1 ORDER BY site_code',[org(req)])).rows));
router.post('/sites', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO facilities_sites (organisation_id,site_code,name,site_type,address,responsible_user_id,operating_status,commissioned_at,evidence) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[org(req),req.body.siteCode,req.body.name,req.body.siteType,req.body.address||{},req.body.responsibleUserId,req.body.operatingStatus||'active',req.body.commissionedAt||null,req.body.evidence||[]])).rows[0],201));

router.get('/spaces', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM facilities_spaces WHERE organisation_id=$1 ORDER BY space_code',[org(req)])).rows));
router.post('/spaces', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO facilities_spaces (organisation_id,site_id,parent_space_id,space_code,name,space_type,responsible_user_id,capacity,capacity_unit,operating_status,commissioned_at,evidence) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[org(req),req.body.siteId,req.body.parentSpaceId||null,req.body.spaceCode,req.body.name,req.body.spaceType,req.body.responsibleUserId,req.body.capacity||null,req.body.capacityUnit||null,req.body.operatingStatus||'active',req.body.commissionedAt||null,req.body.evidence||[]])).rows[0],201));

router.get('/assets', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM facilities_assets WHERE organisation_id=$1 ORDER BY asset_code',[org(req)])).rows));
router.post('/assets', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO facilities_assets (organisation_id,site_id,space_id,asset_code,name,asset_type,responsible_user_id,acquisition_cost,currency_code,acquired_at,commissioned_at,status,criticality,evidence) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[org(req),req.body.siteId||null,req.body.spaceId||null,req.body.assetCode,req.body.name,req.body.assetType,req.body.responsibleUserId,req.body.acquisitionCost||null,req.body.currencyCode||'CAD',req.body.acquiredAt||null,req.body.commissionedAt||null,req.body.status||'active',req.body.criticality||'normal',req.body.evidence||[]])).rows[0],201));

router.get('/inspections', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM facilities_inspections WHERE organisation_id=$1 ORDER BY inspected_at DESC',[org(req)])).rows));
router.post('/inspections', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO facilities_inspections (organisation_id,subject_type,subject_id,inspection_number,inspected_at,inspector_user_id,findings,deficiencies,corrective_actions,evidence,status,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[org(req),req.body.subjectType,req.body.subjectId,req.body.inspectionNumber,req.body.inspectedAt,req.body.inspectorUserId,req.body.findings||[],req.body.deficiencies||[],req.body.correctiveActions||[],req.body.evidence||[],req.body.status||'completed',req.get('Idempotency-Key')||req.body.idempotencyKey])).rows[0],201));

router.get('/transfers', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM facilities_transfers WHERE organisation_id=$1 ORDER BY created_at DESC',[org(req)])).rows));
router.post('/transfers', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO facilities_transfers (organisation_id,subject_type,subject_id,from_site_id,from_space_id,to_site_id,to_space_id,requested_by_user_id,accepted_by_user_id,reason,transferred_at,evidence,status,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[org(req),req.body.subjectType,req.body.subjectId,req.body.fromSiteId||null,req.body.fromSpaceId||null,req.body.toSiteId||null,req.body.toSpaceId||null,req.body.requestedByUserId,req.body.acceptedByUserId||null,req.body.reason,req.body.transferredAt||null,req.body.evidence||[],req.body.status||'pending',req.get('Idempotency-Key')||req.body.idempotencyKey])).rows[0],201));

router.get('/disposals', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM facilities_disposals WHERE organisation_id=$1 ORDER BY created_at DESC',[org(req)])).rows));
router.post('/disposals', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO facilities_disposals (organisation_id,asset_id,disposal_method,reason,residual_value,currency_code,requested_by_user_id,approved_by_user_id,disposed_at,evidence,status,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[org(req),req.body.assetId,req.body.disposalMethod,req.body.reason,req.body.residualValue||null,req.body.currencyCode||'CAD',req.body.requestedByUserId,req.body.approvedByUserId||null,req.body.disposedAt||null,req.body.evidence||[],req.body.status||'pending',req.get('Idempotency-Key')||req.body.idempotencyKey])).rows[0],201));

router.get('/alerts', (req,res,next) => handle(res,next,async () => (await db.pool.query(`SELECT 'unresolved_transfer' AS alert_type,id,subject_type,subject_id,created_at FROM facilities_transfers WHERE organisation_id=$1 AND status='pending' UNION ALL SELECT 'pending_disposal',id,'asset',asset_id,created_at FROM facilities_disposals WHERE organisation_id=$1 AND status='pending' ORDER BY created_at DESC`,[org(req)])).rows));

module.exports = router;
