const express = require('express');
const db = require('../../../db');
const { organisationValue } = require('../../utils/organisationScope');
require('../../services/business/organizational-performance-transaction.service');

const router = express.Router();
const org = (req) => organisationValue(req.organisationId || req.user?.organisation_id);
const actor = (req) => req.user?.id || req.user?.userId || null;
const key = (req) => req.get('Idempotency-Key') || req.body?.idempotencyKey;
const handle = (res, next, fn, status = 200) => Promise.resolve(fn()).then((data) => res.status(status).json(data)).catch(next);

router.get('/objectives', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM performance_objectives WHERE organisation_id=$1 ORDER BY period_end DESC',[org(req)])).rows));
router.post('/objectives', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO performance_objectives (organisation_id,objective_number,title,description,owner_user_id,parent_objective_id,perspective,status,priority,period_start,period_end,baseline,target,unit) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[org(req),req.body.objectiveNumber,req.body.title,req.body.description,req.body.ownerUserId||actor(req),req.body.parentObjectiveId||null,req.body.perspective,req.body.status||'draft',req.body.priority||'medium',req.body.periodStart,req.body.periodEnd,req.body.baseline??null,req.body.target??null,req.body.unit||null])).rows[0],201));
router.post('/objectives/:id/approve', (req,res,next) => handle(res,next,async () => (await db.pool.query(`UPDATE performance_objectives SET status='active',approved_by_user_id=$1,approved_at=NOW(),updated_at=NOW() WHERE id=$2 AND organisation_id=$3 RETURNING *`,[req.body.approvedByUserId||actor(req),req.params.id,org(req)])).rows[0]));

router.get('/indicators', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM performance_indicators WHERE organisation_id=$1 ORDER BY created_at DESC',[org(req)])).rows));
router.post('/indicators', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO performance_indicators (organisation_id,objective_id,indicator_number,name,definition,formula,source_system,owner_user_id,direction,frequency,unit,baseline,target,warning_threshold,critical_threshold,tolerance_low,tolerance_high) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING *`,[org(req),req.body.objectiveId,req.body.indicatorNumber,req.body.name,req.body.definition,req.body.formula,req.body.sourceSystem,req.body.ownerUserId||actor(req),req.body.direction,req.body.frequency,req.body.unit,req.body.baseline??null,req.body.target,req.body.warningThreshold??null,req.body.criticalThreshold??null,req.body.toleranceLow??null,req.body.toleranceHigh??null])).rows[0],201));

router.get('/measurements', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM performance_measurements WHERE organisation_id=$1 ORDER BY measured_at DESC',[org(req)])).rows));
router.post('/measurements', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO performance_measurements (organisation_id,indicator_id,measured_at,value,status,source_reference,evidence,measured_by_user_id,commentary,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[org(req),req.body.indicatorId,req.body.measuredAt,req.body.value,req.body.status,req.body.sourceReference,req.body.evidence||[],req.body.measuredByUserId||actor(req),req.body.commentary||null,key(req)])).rows[0],201));

router.get('/reviews', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM performance_reviews WHERE organisation_id=$1 ORDER BY review_date DESC',[org(req)])).rows));
router.post('/reviews', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO performance_reviews (organisation_id,objective_id,review_number,review_date,reviewer_user_id,overall_status,analysis,decisions,evidence,next_review_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[org(req),req.body.objectiveId,req.body.reviewNumber,req.body.reviewDate,req.body.reviewerUserId||actor(req),req.body.overallStatus,req.body.analysis,req.body.decisions||[],req.body.evidence||[],req.body.nextReviewAt||null])).rows[0],201));

router.get('/improvement-plans', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM performance_improvement_plans WHERE organisation_id=$1 ORDER BY due_at',[org(req)])).rows));
router.post('/improvement-plans', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO performance_improvement_plans (organisation_id,objective_id,indicator_id,plan_number,title,root_cause,action_plan,owner_user_id,due_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[org(req),req.body.objectiveId||null,req.body.indicatorId||null,req.body.planNumber,req.body.title,req.body.rootCause,req.body.actionPlan||[],req.body.ownerUserId||actor(req),req.body.dueAt])).rows[0],201));
router.post('/improvement-plans/:id/transition', (req,res,next) => handle(res,next,async () => (await db.pool.query(`UPDATE performance_improvement_plans SET status=$1,implementation_result=$2,implementation_evidence=$3,effectiveness_result=$4,verification_evidence=$5,verified_by_user_id=$6,verified_at=CASE WHEN $1 IN ('verified','closed') THEN NOW() ELSE verified_at END,closed_at=CASE WHEN $1='closed' THEN NOW() ELSE closed_at END,updated_at=NOW() WHERE id=$7 AND organisation_id=$8 RETURNING *`,[req.body.action,req.body.implementationResult||null,req.body.implementationEvidence||[],req.body.effectivenessResult||null,req.body.verificationEvidence||[],req.body.verifiedByUserId||null,req.params.id,org(req)])).rows[0]));

router.get('/alerts', (req,res,next) => handle(res,next,async () => (await db.pool.query(`SELECT 'objective_at_risk' AS alert_type,id,objective_number AS reference,period_end AS due_at FROM performance_objectives WHERE organisation_id=$1 AND status='at_risk' UNION ALL SELECT 'improvement_overdue',id,plan_number,due_at FROM performance_improvement_plans WHERE organisation_id=$1 AND due_at<CURRENT_DATE AND status NOT IN ('verified','closed','cancelled') ORDER BY due_at`,[org(req)])).rows));

module.exports = router;
