const express = require('express');
const db = require('../../../db');
const { organisationValue } = require('../../utils/organisationScope');
require('../../services/business/organizational-governance-transaction.service');

const router = express.Router();
const org = (req) => organisationValue(req.organisationId || req.user?.organisation_id);
const actor = (req) => req.user?.id || req.user?.userId || null;
const key = (req) => req.get('Idempotency-Key') || req.body?.idempotencyKey;
const handle = (res, next, fn, status = 200) => Promise.resolve(fn()).then((data) => res.status(status).json(data)).catch(next);

router.get('/units', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM governance_units WHERE organisation_id=$1 ORDER BY unit_code',[org(req)])).rows));
router.post('/units', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO governance_units (organisation_id,parent_unit_id,unit_code,name,unit_type,leader_user_id,mandate,status,effective_from,effective_to) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[org(req),req.body.parentUnitId||null,req.body.unitCode,req.body.name,req.body.unitType,req.body.leaderUserId,req.body.mandate,req.body.status||'active',req.body.effectiveFrom,req.body.effectiveTo||null])).rows[0],201));

router.get('/delegations', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM governance_delegations WHERE organisation_id=$1 ORDER BY starts_at DESC',[org(req)])).rows));
router.post('/delegations', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO governance_delegations (organisation_id,delegation_number,delegator_user_id,delegate_user_id,authority_type,scope,financial_limit,starts_at,ends_at,reason,evidence,status,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[org(req),req.body.delegationNumber,req.body.delegatorUserId||actor(req),req.body.delegateUserId,req.body.authorityType,req.body.scope||[],req.body.financialLimit||null,req.body.startsAt,req.body.endsAt,req.body.reason,req.body.evidence||[],req.body.status||'active',key(req)])).rows[0],201));

router.get('/committees', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM governance_committees WHERE organisation_id=$1 ORDER BY name',[org(req)])).rows));
router.post('/committees', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO governance_committees (organisation_id,committee_code,name,mandate,chair_user_id,secretary_user_id,quorum_required,members,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[org(req),req.body.committeeCode,req.body.name,req.body.mandate,req.body.chairUserId,req.body.secretaryUserId||null,req.body.quorumRequired,req.body.members||[],req.body.status||'active'])).rows[0],201));

router.get('/meetings', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM governance_meetings WHERE organisation_id=$1 ORDER BY scheduled_at DESC',[org(req)])).rows));
router.post('/meetings', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO governance_meetings (organisation_id,committee_id,meeting_number,scheduled_at,attendees,agenda,minutes,decisions,evidence,quorum_met,status,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[org(req),req.body.committeeId,req.body.meetingNumber,req.body.scheduledAt,req.body.attendees||[],req.body.agenda||[],req.body.minutes||null,req.body.decisions||[],req.body.evidence||[],Boolean(req.body.quorumMet),req.body.status||'scheduled',key(req)])).rows[0],201));

router.get('/decisions', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM governance_decisions WHERE organisation_id=$1 ORDER BY created_at DESC',[org(req)])).rows));
router.post('/decisions', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO governance_decisions (organisation_id,meeting_id,decision_number,category,title,context,analysis,decision_text,justification,impacts,risks,evidence,author_user_id,status,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,[org(req),req.body.meetingId||null,req.body.decisionNumber,req.body.category,req.body.title,req.body.context,req.body.analysis,req.body.decisionText,req.body.justification,req.body.impacts||[],req.body.risks||[],req.body.evidence||[],req.body.authorUserId||actor(req),req.body.status||'draft',key(req)])).rows[0],201));
router.post('/decisions/:id/approve', (req,res,next) => handle(res,next,async () => (await db.pool.query(`UPDATE governance_decisions SET approver_user_id=$1,effective_at=$2,status='approved',updated_at=NOW() WHERE id=$3 AND organisation_id=$4 RETURNING *`,[req.body.approverUserId||actor(req),req.body.effectiveAt||new Date().toISOString(),req.params.id,org(req)])).rows[0]));

router.get('/policies', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM governance_policies WHERE organisation_id=$1 ORDER BY policy_number,version DESC',[org(req)])).rows));
router.post('/policies', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO governance_policies (organisation_id,policy_number,title,version,owner_user_id,content_reference,approval_evidence,effective_from,review_due_at,status,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[org(req),req.body.policyNumber,req.body.title,req.body.version,req.body.ownerUserId||actor(req),req.body.contentReference,req.body.approvalEvidence||[],req.body.effectiveFrom||null,req.body.reviewDueAt||null,req.body.status||'draft',key(req)])).rows[0],201));

router.get('/conflicts', (req,res,next) => handle(res,next,async () => (await db.pool.query('SELECT * FROM governance_conflicts WHERE organisation_id=$1 ORDER BY created_at DESC',[org(req)])).rows));
router.post('/conflicts', (req,res,next) => handle(res,next,async () => (await db.pool.query(`INSERT INTO governance_conflicts (organisation_id,declarant_user_id,conflict_number,subject_type,subject_id,description,mitigation,evidence,status,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[org(req),req.body.declarantUserId||actor(req),req.body.conflictNumber,req.body.subjectType,req.body.subjectId||null,req.body.description,req.body.mitigation,req.body.evidence||[],req.body.status||'declared',key(req)])).rows[0],201));

router.get('/alerts', (req,res,next) => handle(res,next,async () => (await db.pool.query(`SELECT 'delegation_expiring' AS alert_type,id,delegation_number AS reference,ends_at AS due_at FROM governance_delegations WHERE organisation_id=$1 AND status='active' AND ends_at<=NOW()+INTERVAL '30 days' UNION ALL SELECT 'policy_review_due',id,policy_number,review_due_at::timestamptz FROM governance_policies WHERE organisation_id=$1 AND status='published' AND review_due_at<=CURRENT_DATE+30 ORDER BY due_at`,[org(req)])).rows));

module.exports = router;