'use strict';

const crypto=require('crypto');
const router=require('express').Router();
const { requireOrganisation }=require('../../middleware/organization.middleware');
router.use(requireOrganisation);
const positiveId=(v,l)=>{const id=Number(v);if(!Number.isInteger(id)||id<=0)throw Object.assign(new Error(`${l} invalide.`),{statusCode:400});return id;};

router.get('/',async(req,res,next)=>{try{const {rows}=await req.db.query(`SELECT r.*,p.period_start,p.period_end,p.pay_date FROM payroll_reconciliation_runs r JOIN payroll_runs p ON p.id=r.payroll_run_id AND p.organisation_id=r.organisation_id WHERE r.organisation_id=$1 ORDER BY r.reconciled_at DESC,r.id DESC`,[req.organisationId]);return res.json({reconciliations:rows});}catch(error){return next(error);}});

router.post('/runs/:runId',async(req,res,next)=>{try{const runId=positiveId(req.params.runId,'Cycle');const body=req.body||{};const idempotencyKey=body.idempotencyKey||crypto.randomUUID();const run=await req.db.query(`SELECT id,status,totals FROM payroll_runs WHERE organisation_id=$1 AND id=$2 AND status IN ('approved','paid')`,[req.organisationId,runId]);if(!run.rows[0])return res.status(409).json({message:'Le cycle doit être approuvé ou payé avant rapprochement.'});const deposits=await req.db.query(`SELECT COALESCE(SUM(total_amount),0) AS total FROM payroll_payment_batches WHERE organisation_id=$1 AND payroll_run_id=$2 AND status='confirmed'`,[req.organisationId,runId]);const remittances=await req.db.query(`SELECT COALESCE(SUM(employee_amount+employer_amount),0) AS total FROM payroll_remittances WHERE organisation_id=$1 AND payroll_run_id=$2 AND status='paid'`,[req.organisationId,runId]);const expectedNet=Number(run.rows[0].totals?.net||0);const depositedNet=Number(deposits.rows[0].total||0);const remittedTotal=Number(remittances.rows[0].total||0);const variance=Number((depositedNet-expectedNet).toFixed(2));const findings=[];if(variance!==0)findings.push({code:'deposit_variance',expectedNet,depositedNet,variance});if(body.requirePaidRemittances!==false&&remittedTotal===0)findings.push({code:'missing_paid_remittances'});const status=Math.abs(variance)>0.01?'blocked':findings.length?'warning':'balanced';const evidence=[...(Array.isArray(body.evidence)?body.evidence:[]),{source:'payroll_runs',runId},{source:'payroll_payment_batches',depositedNet},{source:'payroll_remittances',remittedTotal}];const {rows}=await req.db.query(`INSERT INTO payroll_reconciliation_runs (organisation_id,payroll_run_id,expected_net,deposited_net,remitted_total,variance,status,findings,evidence,reconciled_by,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (organisation_id,idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING *`,[req.organisationId,runId,expectedNet,depositedNet,remittedTotal,variance,status,findings,evidence,req.user?.id||null,idempotencyKey]);return res.status(201).json({reconciliation:rows[0]});}catch(error){return next(error);}});

router.get('/runs/:runId/summary',async(req,res,next)=>{try{const runId=positiveId(req.params.runId,'Cycle');const [run,deposits,remittances,reconciliations]=await Promise.all([req.db.query(`SELECT id,status,totals FROM payroll_runs WHERE organisation_id=$1 AND id=$2`,[req.organisationId,runId]),req.db.query(`SELECT status,total_amount,payment_count,file_hash,confirmation FROM payroll_payment_batches WHERE organisation_id=$1 AND payroll_run_id=$2 ORDER BY id DESC`,[req.organisationId,runId]),req.db.query(`SELECT authority,remittance_type,status,employee_amount,employer_amount,confirmation_number FROM payroll_remittances WHERE organisation_id=$1 AND payroll_run_id=$2 ORDER BY id DESC`,[req.organisationId,runId]),req.db.query(`SELECT * FROM payroll_reconciliation_runs WHERE organisation_id=$1 AND payroll_run_id=$2 ORDER BY reconciled_at DESC`,[req.organisationId,runId])]);if(!run.rows[0])return res.status(404).json({message:'Cycle de paie introuvable.'});return res.json({run:run.rows[0],deposits:deposits.rows,remittances:remittances.rows,reconciliations:reconciliations.rows});}catch(error){return next(error);}});

module.exports=router;
