'use strict';

const router=require('express').Router();
const { requireOrganisation }=require('../../middleware/organization.middleware');
router.use(requireOrganisation);
const positiveId=(v,l)=>{const id=Number(v);if(!Number.isInteger(id)||id<=0)throw Object.assign(new Error(`${l} invalide.`),{statusCode:400});return id;};

router.get('/',async(req,res,next)=>{try{const {rows}=await req.db.query(`SELECT t.*,e.employee_number,e.legal_name FROM payroll_terminations t JOIN payroll_employees e ON e.id=t.employee_id AND e.organisation_id=t.organisation_id WHERE t.organisation_id=$1 ORDER BY t.last_day_worked DESC,t.id DESC`,[req.organisationId]);return res.json({terminations:rows});}catch(error){return next(error);}});

router.post('/',async(req,res,next)=>{try{const body=req.body||{};const employeeId=positiveId(body.employeeId,'Employé');if(!body.lastDayWorked||!body.reasonCode||!body.finalPayDate)return res.status(400).json({message:'La date de fin, le motif et la date de paie finale sont obligatoires.'});for(const key of ['vacationPayout','severanceAmount','otherAmount'])if(Number(body[key]||0)<0)return res.status(400).json({message:'Les montants de fin d’emploi ne peuvent pas être négatifs.'});const {rows}=await req.db.query(`INSERT INTO payroll_terminations (organisation_id,employee_id,last_day_worked,reason_code,final_pay_date,vacation_payout,severance_amount,other_amount,roe_payload,created_by) SELECT $1,id,$3,$4,$5,$6,$7,$8,$9,$10 FROM payroll_employees WHERE organisation_id=$1 AND id=$2 ON CONFLICT (organisation_id,employee_id,last_day_worked) DO UPDATE SET reason_code=EXCLUDED.reason_code,final_pay_date=EXCLUDED.final_pay_date,vacation_payout=EXCLUDED.vacation_payout,severance_amount=EXCLUDED.severance_amount,other_amount=EXCLUDED.other_amount,roe_payload=EXCLUDED.roe_payload RETURNING *`,[req.organisationId,employeeId,body.lastDayWorked,body.reasonCode,body.finalPayDate,Number(body.vacationPayout||0),Number(body.severanceAmount||0),Number(body.otherAmount||0),body.roePayload||{},req.user?.id||null]);if(!rows[0])return res.status(404).json({message:'Employé introuvable.'});return res.status(201).json({termination:rows[0]});}catch(error){return next(error);}});

router.post('/:id/:action',async(req,res,next)=>{try{const id=positiveId(req.params.id,'Fin d’emploi');const transitions={approve:{from:['draft'],to:'approved'},issue:{from:['approved'],to:'issued'},cancel:{from:['draft','approved'],to:'cancelled'}};const transition=transitions[req.params.action];if(!transition)return res.status(404).json({message:'Action de fin d’emploi inconnue.'});if(req.params.action==='issue'&&(!req.body?.roePayload||Object.keys(req.body.roePayload).length===0))return res.status(400).json({message:'Le relevé d’emploi doit être fourni avant l’émission.'});const {rows}=await req.db.query(`UPDATE payroll_terminations SET status=$3,roe_payload=CASE WHEN $3='issued' THEN $4 ELSE roe_payload END,issued_at=CASE WHEN $3='issued' THEN NOW() ELSE issued_at END WHERE organisation_id=$1 AND id=$2 AND status=ANY($5::text[]) RETURNING *`,[req.organisationId,id,transition.to,req.body?.roePayload||{},transition.from]);if(!rows[0])return res.status(409).json({message:'La fin d’emploi est introuvable ou sa transition est invalide.'});if(transition.to==='issued')await req.db.query(`UPDATE payroll_employees SET employment_status='terminated',termination_date=$3,updated_at=NOW() WHERE organisation_id=$1 AND id=$2`,[req.organisationId,rows[0].employee_id,rows[0].last_day_worked]);return res.json({termination:rows[0]});}catch(error){return next(error);}});

module.exports=router;
