'use strict';

const crypto=require('crypto');
const router=require('express').Router();
const { requireOrganisation }=require('../../middleware/organization.middleware');
router.use(requireOrganisation);
const positiveId=(v,l)=>{const id=Number(v);if(!Number.isInteger(id)||id<=0)throw Object.assign(new Error(`${l} invalide.`),{statusCode:400});return id;};

router.get('/',async(req,res,next)=>{try{const taxYear=req.query.taxYear?Number(req.query.taxYear):null;const {rows}=await req.db.query(`SELECT s.*,e.employee_number,e.legal_name FROM payroll_year_end_slips s JOIN payroll_employees e ON e.id=s.employee_id AND e.organisation_id=s.organisation_id WHERE s.organisation_id=$1 AND ($2::int IS NULL OR s.tax_year=$2) ORDER BY s.tax_year DESC,e.legal_name,s.slip_type`,[req.organisationId,taxYear]);return res.json({slips:rows});}catch(error){return next(error);}});

router.post('/',async(req,res,next)=>{try{const body=req.body||{};const employeeId=positiveId(body.employeeId,'Employé');const taxYear=Number(body.taxYear);if(!Number.isInteger(taxYear)||taxYear<2000||!['T4','RL1','T4A','RL2'].includes(body.slipType))return res.status(400).json({message:'L’année ou le type de feuillet est invalide.'});if(!body.boxes||typeof body.boxes!=='object'||Array.isArray(body.boxes))return res.status(400).json({message:'Les cases fiscales sont obligatoires.'});const sourceHash=body.sourceHash||crypto.createHash('sha256').update(JSON.stringify({employeeId,taxYear,slipType:body.slipType,boxes:body.boxes,totals:body.totals||{}})).digest('hex');const {rows}=await req.db.query(`INSERT INTO payroll_year_end_slips (organisation_id,employee_id,tax_year,slip_type,boxes,totals,source_hash,created_by) SELECT $1,id,$3,$4,$5,$6,$7,$8 FROM payroll_employees WHERE organisation_id=$1 AND id=$2 ON CONFLICT (organisation_id,employee_id,tax_year,slip_type,source_hash) DO UPDATE SET source_hash=EXCLUDED.source_hash RETURNING *`,[req.organisationId,employeeId,taxYear,body.slipType,body.boxes,body.totals||{},sourceHash,req.user?.id||null]);if(!rows[0])return res.status(404).json({message:'Employé introuvable.'});return res.status(201).json({slip:rows[0]});}catch(error){return next(error);}});

router.post('/:id/:action',async(req,res,next)=>{try{const id=positiveId(req.params.id,'Feuillet');const transitions={validate:{from:['draft','amended'],to:'validated'},issue:{from:['validated'],to:'issued'},cancel:{from:['draft','validated','issued','amended'],to:'cancelled'}};const transition=transitions[req.params.action];if(!transition)return res.status(404).json({message:'Action de feuillet inconnue.'});if(req.params.action==='issue'&&!String(req.body?.approvalReference||'').trim())return res.status(400).json({message:'Une référence d’approbation humaine est obligatoire avant émission.'});const {rows}=await req.db.query(`UPDATE payroll_year_end_slips SET status=$3,issued_at=CASE WHEN $3='issued' THEN NOW() ELSE issued_at END,totals=CASE WHEN $3='issued' THEN totals||jsonb_build_object('approvalReference',$4::text) ELSE totals END WHERE organisation_id=$1 AND id=$2 AND status=ANY($5::text[]) RETURNING *`,[req.organisationId,id,transition.to,String(req.body?.approvalReference||''),transition.from]);if(!rows[0])return res.status(409).json({message:'Le feuillet est introuvable ou sa transition est invalide.'});return res.json({slip:rows[0]});}catch(error){return next(error);}});

router.post('/:id/amend',async(req,res,next)=>{try{const id=positiveId(req.params.id,'Feuillet');const original=await req.db.query(`SELECT * FROM payroll_year_end_slips WHERE organisation_id=$1 AND id=$2 AND status='issued'`,[req.organisationId,id]);if(!original.rows[0])return res.status(409).json({message:'Seul un feuillet émis peut être corrigé.'});const sourceHash=crypto.createHash('sha256').update(JSON.stringify(req.body?.boxes||{})).digest('hex');const {rows}=await req.db.query(`INSERT INTO payroll_year_end_slips (organisation_id,employee_id,tax_year,slip_type,status,boxes,totals,source_hash,amended_from_id,created_by) VALUES ($1,$2,$3,$4,'amended',$5,$6,$7,$8,$9) RETURNING *`,[req.organisationId,original.rows[0].employee_id,original.rows[0].tax_year,original.rows[0].slip_type,req.body?.boxes||{},req.body?.totals||{},sourceHash,id,req.user?.id||null]);return res.status(201).json({slip:rows[0]});}catch(error){return next(error);}});

module.exports=router;
